#!/bin/bash

function check_error6 {
  if [[ ! $1 =~ ^[0-9]+$ ]]
  then
    error=6
  else
    if [ $1 -gt 100 ] || [ $1 -lt 0 ]
    then
      error=6
    fi
  fi
  echo $error
}

function count_dot {
  count=0
  for (( i=0; i < ${#1}; i++ )) 
  do
    if [[ ${1:i:1} == '.' ]]
    then
      count=$[ $count + 1 ]
    fi
  done
  echo $count
}

function check_error5 {
  if [[ ! $1 =~ ^[A-Za-z.]+$ ]]
  then
    error=5
  elif [ $( count_dot $1 ) -ne 1 ]
  then
    error=5
  else
    IFS='.'
    read -a array <<< $1
    if [ ${#array[0]} -gt 7 ] || [ ${#array[1]} -gt 3 ]
    then
      error=5
    fi
  fi
  echo $error
}

function check_error42 {
  if [[ ! $1 =~ ^[0-9]+$ ]]
  then
    error=$2
  fi
  echo $error
}

function check_error3 {
  if [[ ! $1 =~ ^[A-Za-z]+$ ]]
  then
   error=3
  elif [[ ${#1} -gt 7 ]]
  then
    error=3
  fi
  echo $error
}

function check_error1 {
  str="$1"
  if [[ ${str:0:1} != "/" ]]
  then
    error=1
  elif [ -f $1 ]
  then
    error=1
  fi
  echo $error
}

function check_param {
  error=0
  if [ $# -ne 6 ]
  then
    error=7
  else
    error=$( check_error6 $6 )
    error=$( check_error5 $5 )
    error=$( check_error42 $4 4 )
    error=$( check_error3 $3 )
    error=$( check_error42 $2 2 )
    error=$( check_error1 $1 )
  fi
  echo $error
}
