#!/bin/bash

function check_param {
  error=0
  if [ $# -ne 1 ]
  then
    error=1
  else
    if [[ $1 != 1 ]] && [[ $1 != 2 ]] && [[ $1 != 3 ]] && [[ $1 != 4 ]]
    then
      error=1
    fi
  fi
  echo $error
}
